dont build for now

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,60 +1,59 @@
-name: Test
-
-on:
-  push:
-    branches:
-      - main
-jobs:
-  test:
-    runs-on: buildjet-4vcpu-ubuntu-2204-arm
-#   runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: install argocd cli
-        run: |
-          curl -sSL -o argocd-linux-arm64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64
-          sudo install -m 555 argocd-linux-arm64 /usr/local/bin/argocd
-          rm -fv argocd-linux-amd64
-      - name: install minikube
-        run: |
-          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_arm64.deb
-          sudo dpkg -i minikube_latest_arm64.deb
-          rm -fv minikube_latest_arm64.deb
-      - uses: azure/setup-kubectl@v3
-        id: install
-      - name: run argocd on minikube
-        run: |
-          set -o xtrace
-          sudo snap install helm --classic
-          minikube start --driver=docker
-          kubectl apply -f - <<EOF
-          apiVersion: v1
-          kind: Secret
-          metadata:
-            name: github-token
-          type: Opaque
-          stringData:
-            token: ${{ secrets.GITHUB_TOKEN }}
-          EOF
-          helm dependency update charts/bootstrap-argo-cd
-          helm install -n argocd --create-namespace argo-cd charts/bootstrap-argo-cd
-          kubectl rollout -n argocd status --watch deployment argo-cd-argocd-server
-          argocd login cd.argoproj.io --core
-          kubectl apply -n argocd -f charts/root/templates/root.yaml
-          kubectl create namespace okapp
-          kubectl config set-context --current --namespace=argocd
-          for application_name in root argo-cd ok gatus ; do
-            argocd app sync $application_name || echo syncing $application_name failed
-            argocd app wait --operation --timeout 60 --sync --health $application_name || echo waiting for $application_name failed
-          done
-      #     kubectl port-forward service/springboot-helm-prod-spring-boot-helm-demo -n default 3000:80 &
-      # - name: test application response
-      #   run: |
-      #     curl --retry-connrefused \
-      #       --connect-timeout 5 \
-      #       --max-time 10 \
-      #       --retry 5 \
-      #       --retry-delay 0 \
-      #       --retry-max-time 30 \
-      #       --fail http://localhost:3000/ | \
-      #       grep -q "Hello Application"
+# name: Test
+# on:
+#   push:
+#     branches:
+#       - main
+# jobs:
+#   test:
+#     runs-on: buildjet-4vcpu-ubuntu-2204-arm
+# #   runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v3
+#       - name: install argocd cli
+#         run: |
+#           curl -sSL -o argocd-linux-arm64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64
+#           sudo install -m 555 argocd-linux-arm64 /usr/local/bin/argocd
+#           rm -fv argocd-linux-amd64
+#       - name: install minikube
+#         run: |
+#           curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_arm64.deb
+#           sudo dpkg -i minikube_latest_arm64.deb
+#           rm -fv minikube_latest_arm64.deb
+#       - uses: azure/setup-kubectl@v3
+#         id: install
+#       - name: run argocd on minikube
+#         run: |
+#           set -o xtrace
+#           sudo snap install helm --classic
+#           minikube start --driver=docker
+#           kubectl apply -f - <<EOF
+#           apiVersion: v1
+#           kind: Secret
+#           metadata:
+#             name: github-token
+#           type: Opaque
+#           stringData:
+#             token: ${{ secrets.GITHUB_TOKEN }}
+#           EOF
+#           helm dependency update charts/bootstrap-argo-cd
+#           helm install -n argocd --create-namespace argo-cd charts/bootstrap-argo-cd
+#           kubectl rollout -n argocd status --watch deployment argo-cd-argocd-server
+#           argocd login cd.argoproj.io --core
+#           kubectl apply -n argocd -f charts/root/templates/root.yaml
+#           kubectl create namespace okapp
+#           kubectl config set-context --current --namespace=argocd
+#           for application_name in root argo-cd ok gatus ; do
+#             argocd app sync $application_name || echo syncing $application_name failed
+#             argocd app wait --operation --timeout 60 --sync --health $application_name || echo waiting for $application_name failed
+#           done
+#       #     kubectl port-forward service/springboot-helm-prod-spring-boot-helm-demo -n default 3000:80 &
+#       # - name: test application response
+#       #   run: |
+#       #     curl --retry-connrefused \
+#       #       --connect-timeout 5 \
+#       #       --max-time 10 \
+#       #       --retry 5 \
+#       #       --retry-delay 0 \
+#       #       --retry-max-time 30 \
+#       #       --fail http://localhost:3000/ | \
+#       #       grep -q "Hello Application"
